

  CREATE OR REPLACE FORCE VIEW "GESOALDO"."LISTA_PEDIDOS" ("NOME", "DESCRICAO") AS 
  Select nome, descricao From vendedor v 
join pedido p on v.codvend = p.codvend 
Join itenspedido i on p.numped = i.numped
join produto pr on i.codprod = pr.codprod
order by nome
;


  CREATE OR REPLACE FORCE VIEW "GESOALDO"."PRODUTO_DESCA" ("CODPROD", "DESCRICAO") AS 
  SELECT codprod, descricao FROM produto WHERE descricao like 'A%' WITH CHECK OPTION
;


  CREATE OR REPLACE FORCE VIEW "GESOALDO"."PR_QUILO" ("CODIGO", "DESCRICAO", "UNIDADE") AS 
  Select codprod,descricao,unidade From produto Where unidade = 'KG'
;


  CREATE OR REPLACE FORCE VIEW "GESOALDO"."VEND_SAL" ("CODIGO", "NOME", "SALARIO") AS 
  Select codvend,nome,salariofixo From vendedor WITH READ ONLY
;


  CREATE TABLE "GESOALDO"."ARTISTA" 
   (	"COD_ARTISTA" NUMBER, 
	"NOME_ARTISTA" VARCHAR2(25 BYTE), 
	"CIDADE" VARCHAR2(20 BYTE), 
	"PAIS" VARCHAR2(20 BYTE), 
	"DATA_NASC" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "GESOALDO"."CATEGORIA" 
   (	"COD_CATEG" NUMBER, 
	"DESCRICAO_CATEG" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "GESOALDO"."CLIENTE" 
   (	"CODCLI" NUMBER, 
	"NOME" VARCHAR2(30 BYTE), 
	"ENDERECO" VARCHAR2(30 BYTE), 
	"TELEFONE" VARCHAR2(12 BYTE), 
	"INSCE" VARCHAR2(10 BYTE), 
	"CNPJ" VARCHAR2(10 BYTE), 
	"CIDADE" VARCHAR2(15 BYTE), 
	"UF" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "GESOALDO"."DEPARTAMENTO" 
   (	"CODDEPTO" NUMBER, 
	"NOME" VARCHAR2(20 BYTE), 
	"LOCAL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "GESOALDO"."DISCIPLINA" 
   (	"COD_DISC" NUMBER, 
	"NOME_DISC" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "GESOALDO"."EMPREGADO" 
   (	"MATRICULA" NUMBER, 
	"PRIMEIRONOME" VARCHAR2(15 BYTE), 
	"SOBRENOME" VARCHAR2(15 BYTE), 
	"DATAADMISSAO" DATE, 
	"CARGO" VARCHAR2(30 BYTE), 
	"SALARIO" NUMBER(15,2), 
	"GERENTE" NUMBER, 
	"CODDEPTO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "GESOALDO"."ESTUDIO" 
   (	"COD_ESTUDIO" NUMBER, 
	"NOME_ESTUDIO" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "GESOALDO"."FILME" 
   (	"COD_FILME" NUMBER, 
	"TITULO" VARCHAR2(25 BYTE), 
	"ANO" NUMBER, 
	"DURACAO" NUMBER, 
	"COD_CATEG" NUMBER, 
	"COD_ESTUDIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FORNECEDOR
--------------------------------------------------------

  CREATE TABLE "GESOALDO"."FORNECEDOR" 
   (	"ID_FORNECEDOR" NUMBER, 
	"NOME_FORNECEDOR" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "GESOALDO"."ITENSPEDIDO" 
   (	"NUMPED" NUMBER, 
	"CODPROD" NUMBER, 
	"QUANTIDADE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PEDIDO
--------------------------------------------------------

  CREATE TABLE "GESOALDO"."PEDIDO" 
   (	"NUMPED" NUMBER, 
	"PRAZOENTREGA" NUMBER, 
	"DATA" DATE, 
	"CODCLI" NUMBER, 
	"CODVEND" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "GESOALDO"."PERSONAGEM" 
   (	"COD_ARTISTA" NUMBER, 
	"COD_FILME" NUMBER, 
	"NOME_PERSONAGEM" VARCHAR2(25 BYTE), 
	"CACHE" NUMBER(15,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "GESOALDO"."PRODUTO" 
   (	"CODPROD" NUMBER, 
	"DESCRICAO" VARCHAR2(20 BYTE), 
	"VALOR" NUMBER(10,2), 
	"UNIDADE" CHAR(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "GESOALDO"."PROFESSOR" 
   (	"MATRIC_PROF" VARCHAR2(6 BYTE), 
	"NOME_PROF" VARCHAR2(40 BYTE), 
	"DATA_ADMISSAO" DATE, 
	"COD_DISC" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "GESOALDO"."VENDEDOR" 
   (	"CODVEND" NUMBER, 
	"NOME" VARCHAR2(30 BYTE), 
	"DATANASC" DATE, 
	"SALARIOFIXO" NUMBER(15,2), 
	"FAIXACOMISSAO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into GESOALDO.ARTISTA
SET DEFINE OFF;
Insert into GESOALDO.ARTISTA (COD_ARTISTA,NOME_ARTISTA,CIDADE,PAIS,DATA_NASC) values ('1','Cameron Diaz',null,'USA',to_date('15/07/75','DD/MM/RR'));
Insert into GESOALDO.ARTISTA (COD_ARTISTA,NOME_ARTISTA,CIDADE,PAIS,DATA_NASC) values ('2','Julia Roberts',null,'USA',to_date('20/08/67','DD/MM/RR'));
Insert into GESOALDO.ARTISTA (COD_ARTISTA,NOME_ARTISTA,CIDADE,PAIS,DATA_NASC) values ('3','Brad Pitt',null,null,to_date('05/03/70','DD/MM/RR'));
Insert into GESOALDO.ARTISTA (COD_ARTISTA,NOME_ARTISTA,CIDADE,PAIS,DATA_NASC) values ('4','Mel Gibson',null,null,to_date('06/04/59','DD/MM/RR'));
Insert into GESOALDO.ARTISTA (COD_ARTISTA,NOME_ARTISTA,CIDADE,PAIS,DATA_NASC) values ('5','Russel Crowe',null,'USA',to_date('06/06/62','DD/MM/RR'));
Insert into GESOALDO.ARTISTA (COD_ARTISTA,NOME_ARTISTA,CIDADE,PAIS,DATA_NASC) values ('6','Tom Cruise',null,'USA',to_date('10/09/64','DD/MM/RR'));
Insert into GESOALDO.ARTISTA (COD_ARTISTA,NOME_ARTISTA,CIDADE,PAIS,DATA_NASC) values ('7','Antonio Fagundes','Rio de Janeiro','Brasil',to_date('12/10/58','DD/MM/RR'));
Insert into GESOALDO.ARTISTA (COD_ARTISTA,NOME_ARTISTA,CIDADE,PAIS,DATA_NASC) values ('8','Raul J�lia',null,'Porto Rico',to_date('09/03/40','DD/MM/RR'));
REM INSERTING into GESOALDO.CATEGORIA
SET DEFINE OFF;
Insert into GESOALDO.CATEGORIA (COD_CATEG,DESCRICAO_CATEG) values ('1','Aventura');
Insert into GESOALDO.CATEGORIA (COD_CATEG,DESCRICAO_CATEG) values ('2','Romance');
Insert into GESOALDO.CATEGORIA (COD_CATEG,DESCRICAO_CATEG) values ('3','Com�dia');
Insert into GESOALDO.CATEGORIA (COD_CATEG,DESCRICAO_CATEG) values ('4','A��o');
Insert into GESOALDO.CATEGORIA (COD_CATEG,DESCRICAO_CATEG) values ('5','Suspense');
Insert into GESOALDO.CATEGORIA (COD_CATEG,DESCRICAO_CATEG) values ('6','Drama');
Insert into GESOALDO.CATEGORIA (COD_CATEG,DESCRICAO_CATEG) values ('7','Fic��o Cient�fica');
Insert into GESOALDO.CATEGORIA (COD_CATEG,DESCRICAO_CATEG) values ('8','Drama');
REM INSERTING into GESOALDO.CLIENTE
SET DEFINE OFF;
Insert into GESOALDO.CLIENTE (CODCLI,NOME,ENDERECO,TELEFONE,INSCE,CNPJ,CIDADE,UF) values ('1','Claudia Dias',null,null,'564325','786534','Recife','PE');
Insert into GESOALDO.CLIENTE (CODCLI,NOME,ENDERECO,TELEFONE,INSCE,CNPJ,CIDADE,UF) values ('2','Joaquim Moraes','Epitacio Pessoa, 123','32425643','500925','789004','Joao Pessoa','PB');
Insert into GESOALDO.CLIENTE (CODCLI,NOME,ENDERECO,TELEFONE,INSCE,CNPJ,CIDADE,UF) values ('3','Janaina Rodrigues','Rui Carneiro, 342',null,'764325','386534','Joao Pessoa','PB');
Insert into GESOALDO.CLIENTE (CODCLI,NOME,ENDERECO,TELEFONE,INSCE,CNPJ,CIDADE,UF) values ('4','Maria Portela','Boa Viagem, 345','76435678',null,null,'Recife','PE');
Insert into GESOALDO.CLIENTE (CODCLI,NOME,ENDERECO,TELEFONE,INSCE,CNPJ,CIDADE,UF) values ('5','Ana Moura','Nego, 321','32465432','87325','780978','Joao Pessoa','PB');
Insert into GESOALDO.CLIENTE (CODCLI,NOME,ENDERECO,TELEFONE,INSCE,CNPJ,CIDADE,UF) values ('6','Cassandra Doura',null,null,'786525','79876','Recife','PE');
Insert into GESOALDO.CLIENTE (CODCLI,NOME,ENDERECO,TELEFONE,INSCE,CNPJ,CIDADE,UF) values ('7','Cicero Novaes',null,null,'123525','432534','Natal','RN');
Insert into GESOALDO.CLIENTE (CODCLI,NOME,ENDERECO,TELEFONE,INSCE,CNPJ,CIDADE,UF) values ('8','Marcos Araruna','Sergipe,267','43265432','900325','800534','Joao Pessoa','PB');
REM INSERTING into GESOALDO.DEPARTAMENTO
SET DEFINE OFF;
Insert into GESOALDO.DEPARTAMENTO (CODDEPTO,NOME,LOCAL) values ('1','Inform�tica','Sede');
Insert into GESOALDO.DEPARTAMENTO (CODDEPTO,NOME,LOCAL) values ('2','Pessoal','Sede');
Insert into GESOALDO.DEPARTAMENTO (CODDEPTO,NOME,LOCAL) values ('3','Marketing','Praia');
REM INSERTING into GESOALDO.DISCIPLINA
SET DEFINE OFF;
Insert into GESOALDO.DISCIPLINA (COD_DISC,NOME_DISC) values ('1','BD1');
Insert into GESOALDO.DISCIPLINA (COD_DISC,NOME_DISC) values ('2','Sistemas Operacionais');
REM INSERTING into GESOALDO.EMPREGADO
SET DEFINE OFF;
Insert into GESOALDO.EMPREGADO (MATRICULA,PRIMEIRONOME,SOBRENOME,DATAADMISSAO,CARGO,SALARIO,GERENTE,CODDEPTO) values ('1','J�ao','Guedes',to_date('12/10/17','DD/MM/RR'),'Analista de Sistemas Junior','1400',null,'1');
Insert into GESOALDO.EMPREGADO (MATRICULA,PRIMEIRONOME,SOBRENOME,DATAADMISSAO,CARGO,SALARIO,GERENTE,CODDEPTO) values ('2','Jos�','Batista',to_date('12/10/17','DD/MM/RR'),'Analista de Sistemas Pleno','2200','1','1');
Insert into GESOALDO.EMPREGADO (MATRICULA,PRIMEIRONOME,SOBRENOME,DATAADMISSAO,CARGO,SALARIO,GERENTE,CODDEPTO) values ('3','Ana Maria','Silva',to_date('12/10/17','DD/MM/RR'),'Analista de Sistemas Junior','1400','1','1');
Insert into GESOALDO.EMPREGADO (MATRICULA,PRIMEIRONOME,SOBRENOME,DATAADMISSAO,CARGO,SALARIO,GERENTE,CODDEPTO) values ('4','Ricardo','Neves',to_date('12/10/17','DD/MM/RR'),'Analista de Sistemas Pleno','2200','2','1');
Insert into GESOALDO.EMPREGADO (MATRICULA,PRIMEIRONOME,SOBRENOME,DATAADMISSAO,CARGO,SALARIO,GERENTE,CODDEPTO) values ('5','Valter','Moura',to_date('12/10/17','DD/MM/RR'),'Analista de Suporte Junior','1400','2','1');
Insert into GESOALDO.EMPREGADO (MATRICULA,PRIMEIRONOME,SOBRENOME,DATAADMISSAO,CARGO,SALARIO,GERENTE,CODDEPTO) values ('6','Mariana','Oliveira',to_date('12/10/17','DD/MM/RR'),'Designer de Interface','1800','1','1');
REM INSERTING into GESOALDO.ESTUDIO
SET DEFINE OFF;
Insert into GESOALDO.ESTUDIO (COD_ESTUDIO,NOME_ESTUDIO) values ('1','Paramount');
Insert into GESOALDO.ESTUDIO (COD_ESTUDIO,NOME_ESTUDIO) values ('2','Disney');
Insert into GESOALDO.ESTUDIO (COD_ESTUDIO,NOME_ESTUDIO) values ('3','Universal');
REM INSERTING into GESOALDO.FILME
SET DEFINE OFF;
Insert into GESOALDO.FILME (COD_FILME,TITULO,ANO,DURACAO,COD_CATEG,COD_ESTUDIO) values ('1','Encontro Explosivo','2010','134','4','1');
Insert into GESOALDO.FILME (COD_FILME,TITULO,ANO,DURACAO,COD_CATEG,COD_ESTUDIO) values ('2','O Besouro Verde','2010','155','1','1');
Insert into GESOALDO.FILME (COD_FILME,TITULO,ANO,DURACAO,COD_CATEG,COD_ESTUDIO) values ('3','Comer, Rezar, Amar','2010','177','2','1');
Insert into GESOALDO.FILME (COD_FILME,TITULO,ANO,DURACAO,COD_CATEG,COD_ESTUDIO) values ('4','Bastardos Ingl�rios','2009','122','4','1');
Insert into GESOALDO.FILME (COD_FILME,TITULO,ANO,DURACAO,COD_CATEG,COD_ESTUDIO) values ('5','Sr e Sra Smith','2005','119','4','2');
Insert into GESOALDO.FILME (COD_FILME,TITULO,ANO,DURACAO,COD_CATEG,COD_ESTUDIO) values ('6','O Fim da Escurid�o','2009','100','6','1');
Insert into GESOALDO.FILME (COD_FILME,TITULO,ANO,DURACAO,COD_CATEG,COD_ESTUDIO) values ('7','Homem Aranha','2017','100','1','1');
Insert into GESOALDO.FILME (COD_FILME,TITULO,ANO,DURACAO,COD_CATEG,COD_ESTUDIO) values ('8','Efeito Borboleta','2006','130','6','3');
Insert into GESOALDO.FILME (COD_FILME,TITULO,ANO,DURACAO,COD_CATEG,COD_ESTUDIO) values ('9','Street Fight','2006','120','1','3');
REM INSERTING into GESOALDO.FORNECEDOR
SET DEFINE OFF;
REM INSERTING into GESOALDO.ITENSPEDIDO
SET DEFINE OFF;
Insert into GESOALDO.ITENSPEDIDO (NUMPED,CODPROD,QUANTIDADE) values ('205','25','35');
Insert into GESOALDO.ITENSPEDIDO (NUMPED,CODPROD,QUANTIDADE) values ('205','22','30');
Insert into GESOALDO.ITENSPEDIDO (NUMPED,CODPROD,QUANTIDADE) values ('205','15','10');
Insert into GESOALDO.ITENSPEDIDO (NUMPED,CODPROD,QUANTIDADE) values ('120','45','35');
Insert into GESOALDO.ITENSPEDIDO (NUMPED,CODPROD,QUANTIDADE) values ('120','44','10');
Insert into GESOALDO.ITENSPEDIDO (NUMPED,CODPROD,QUANTIDADE) values ('123','45','35');
Insert into GESOALDO.ITENSPEDIDO (NUMPED,CODPROD,QUANTIDADE) values ('123','10','10');
REM INSERTING into GESOALDO.PEDIDO
SET DEFINE OFF;
Insert into GESOALDO.PEDIDO (NUMPED,PRAZOENTREGA,DATA,CODCLI,CODVEND) values ('205','23',to_date('12/09/16','DD/MM/RR'),'1','1');
Insert into GESOALDO.PEDIDO (NUMPED,PRAZOENTREGA,DATA,CODCLI,CODVEND) values ('120','10',to_date('21/09/16','DD/MM/RR'),'2','1');
Insert into GESOALDO.PEDIDO (NUMPED,PRAZOENTREGA,DATA,CODCLI,CODVEND) values ('222','5',to_date('25/09/16','DD/MM/RR'),'3','4');
Insert into GESOALDO.PEDIDO (NUMPED,PRAZOENTREGA,DATA,CODCLI,CODVEND) values ('123','2',to_date('28/09/16','DD/MM/RR'),'4','2');
Insert into GESOALDO.PEDIDO (NUMPED,PRAZOENTREGA,DATA,CODCLI,CODVEND) values ('201','3',to_date('28/09/16','DD/MM/RR'),'5','3');
Insert into GESOALDO.PEDIDO (NUMPED,PRAZOENTREGA,DATA,CODCLI,CODVEND) values ('204','3',to_date('26/09/16','DD/MM/RR'),'5','2');
REM INSERTING into GESOALDO.PERSONAGEM
SET DEFINE OFF;
Insert into GESOALDO.PERSONAGEM (COD_ARTISTA,COD_FILME,NOME_PERSONAGEM,CACHE) values ('1','1','Natalie','10000');
Insert into GESOALDO.PERSONAGEM (COD_ARTISTA,COD_FILME,NOME_PERSONAGEM,CACHE) values ('1','2','Tom','10000');
Insert into GESOALDO.PERSONAGEM (COD_ARTISTA,COD_FILME,NOME_PERSONAGEM,CACHE) values ('5','3','John','10000');
Insert into GESOALDO.PERSONAGEM (COD_ARTISTA,COD_FILME,NOME_PERSONAGEM,CACHE) values ('3','2','Ana','6000');
Insert into GESOALDO.PERSONAGEM (COD_ARTISTA,COD_FILME,NOME_PERSONAGEM,CACHE) values ('2','1','Kate','11000');
Insert into GESOALDO.PERSONAGEM (COD_ARTISTA,COD_FILME,NOME_PERSONAGEM,CACHE) values ('6','4','Mel','8000');
Insert into GESOALDO.PERSONAGEM (COD_ARTISTA,COD_FILME,NOME_PERSONAGEM,CACHE) values ('8','9','Bison','50000');
REM INSERTING into GESOALDO.PRODUTO
SET DEFINE OFF;
Insert into GESOALDO.PRODUTO (CODPROD,DESCRICAO,VALOR,UNIDADE) values ('25','Queijo','12','KG');
Insert into GESOALDO.PRODUTO (CODPROD,DESCRICAO,VALOR,UNIDADE) values ('22','Chocolate','4,12','G ');
Insert into GESOALDO.PRODUTO (CODPROD,DESCRICAO,VALOR,UNIDADE) values ('15','Leite','5','L ');
Insert into GESOALDO.PRODUTO (CODPROD,DESCRICAO,VALOR,UNIDADE) values ('45','Linho','20','M ');
Insert into GESOALDO.PRODUTO (CODPROD,DESCRICAO,VALOR,UNIDADE) values ('44','Feijao','4','KG');
Insert into GESOALDO.PRODUTO (CODPROD,DESCRICAO,VALOR,UNIDADE) values ('10','Acucar','1','KG');
Insert into GESOALDO.PRODUTO (CODPROD,DESCRICAO,VALOR,UNIDADE) values ('11','Acucar Mascavo','1,2','KG');
Insert into GESOALDO.PRODUTO (CODPROD,DESCRICAO,VALOR,UNIDADE) values ('41','Azeite',null,null);
REM INSERTING into GESOALDO.PROFESSOR
SET DEFINE OFF;
Insert into GESOALDO.PROFESSOR (MATRIC_PROF,NOME_PROF,DATA_ADMISSAO,COD_DISC) values ('1','Cristiane',null,'1');
Insert into GESOALDO.PROFESSOR (MATRIC_PROF,NOME_PROF,DATA_ADMISSAO,COD_DISC) values ('2','Damires',null,'1');
Insert into GESOALDO.PROFESSOR (MATRIC_PROF,NOME_PROF,DATA_ADMISSAO,COD_DISC) values ('3','Luciana',null,'2');
REM INSERTING into GESOALDO.VENDEDOR
SET DEFINE OFF;
Insert into GESOALDO.VENDEDOR (CODVEND,NOME,DATANASC,SALARIOFIXO,FAIXACOMISSAO) values ('1','Juan Gomes',to_date('28/07/78','DD/MM/RR'),'2300,8','C');
Insert into GESOALDO.VENDEDOR (CODVEND,NOME,DATANASC,SALARIOFIXO,FAIXACOMISSAO) values ('2','Joao Peregrino',to_date('20/05/70','DD/MM/RR'),'3300,8','B');
Insert into GESOALDO.VENDEDOR (CODVEND,NOME,DATANASC,SALARIOFIXO,FAIXACOMISSAO) values ('3','Carla Gomes',to_date('12/02/88','DD/MM/RR'),'5300,8','A');
Insert into GESOALDO.VENDEDOR (CODVEND,NOME,DATANASC,SALARIOFIXO,FAIXACOMISSAO) values ('4','Josefa Cirino',to_date('23/08/80','DD/MM/RR'),'2300,8','C');
Insert into GESOALDO.VENDEDOR (CODVEND,NOME,DATANASC,SALARIOFIXO,FAIXACOMISSAO) values ('5','Ariane Dutra',to_date('28/09/83','DD/MM/RR'),'3300,8','B');


  CREATE UNIQUE INDEX "GESOALDO"."PKVEND" ON "GESOALDO"."VENDEDOR" ("CODVEND") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "GESOALDO"."PK_DISCIPLINA" ON "GESOALDO"."DISCIPLINA" ("COD_DISC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "GESOALDO"."PKDEPTO" ON "GESOALDO"."DEPARTAMENTO" ("CODDEPTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "GESOALDO"."PKCLI" ON "GESOALDO"."CLIENTE" ("CODCLI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "GESOALDO"."PK_ARTISTA" ON "GESOALDO"."ARTISTA" ("COD_ARTISTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "GESOALDO"."PKEMP" ON "GESOALDO"."EMPREGADO" ("MATRICULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "GESOALDO"."PKITENS" ON "GESOALDO"."ITENSPEDIDO" ("CODPROD", "NUMPED") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "GESOALDO"."PK_PROFESSOR" ON "GESOALDO"."PROFESSOR" ("MATRIC_PROF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "GESOALDO"."PK_CATEGORIA" ON "GESOALDO"."CATEGORIA" ("COD_CATEG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "GESOALDO"."PKPROD" ON "GESOALDO"."PRODUTO" ("CODPROD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "GESOALDO"."PKPED" ON "GESOALDO"."PEDIDO" ("NUMPED") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "GESOALDO"."PK_ESTUDIO" ON "GESOALDO"."ESTUDIO" ("COD_ESTUDIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "GESOALDO"."PK_FILME" ON "GESOALDO"."FILME" ("COD_FILME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "GESOALDO"."PK_PERSONAGEM" ON "GESOALDO"."PERSONAGEM" ("COD_ARTISTA", "COD_FILME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  ALTER TABLE "GESOALDO"."FILME" ADD CONSTRAINT "PK_FILME" PRIMARY KEY ("COD_FILME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GESOALDO"."FILME" MODIFY ("COD_FILME" NOT NULL ENABLE);


  ALTER TABLE "GESOALDO"."ITENSPEDIDO" ADD CONSTRAINT "PKITENS" PRIMARY KEY ("CODPROD", "NUMPED")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;


  ALTER TABLE "GESOALDO"."CLIENTE" ADD CONSTRAINT "PKCLI" PRIMARY KEY ("CODCLI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;


  ALTER TABLE "GESOALDO"."PEDIDO" ADD CONSTRAINT "PKPED" PRIMARY KEY ("NUMPED")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;


  ALTER TABLE "GESOALDO"."DEPARTAMENTO" ADD CONSTRAINT "PKDEPTO" PRIMARY KEY ("CODDEPTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;


  ALTER TABLE "GESOALDO"."FORNECEDOR" ADD CONSTRAINT "CHECK_FORNECEDOR" CHECK (id_fornecedor BETWEEN 100 and 9999) ENABLE;


  ALTER TABLE "GESOALDO"."VENDEDOR" ADD CONSTRAINT "PKVEND" PRIMARY KEY ("CODVEND")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;


  ALTER TABLE "GESOALDO"."ARTISTA" ADD CONSTRAINT "PK_ARTISTA" PRIMARY KEY ("COD_ARTISTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GESOALDO"."ARTISTA" MODIFY ("COD_ARTISTA" NOT NULL ENABLE);


  ALTER TABLE "GESOALDO"."PRODUTO" ADD CONSTRAINT "PKPROD" PRIMARY KEY ("CODPROD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;


  ALTER TABLE "GESOALDO"."DISCIPLINA" ADD CONSTRAINT "PK_DISCIPLINA" PRIMARY KEY ("COD_DISC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GESOALDO"."DISCIPLINA" MODIFY ("COD_DISC" NOT NULL ENABLE);


  ALTER TABLE "GESOALDO"."PROFESSOR" ADD CONSTRAINT "PK_PROFESSOR" PRIMARY KEY ("MATRIC_PROF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GESOALDO"."PROFESSOR" MODIFY ("MATRIC_PROF" NOT NULL ENABLE);


  ALTER TABLE "GESOALDO"."EMPREGADO" ADD CONSTRAINT "PKEMP" PRIMARY KEY ("MATRICULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;


  ALTER TABLE "GESOALDO"."CATEGORIA" ADD CONSTRAINT "PK_CATEGORIA" PRIMARY KEY ("COD_CATEG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GESOALDO"."CATEGORIA" MODIFY ("COD_CATEG" NOT NULL ENABLE);

  ALTER TABLE "GESOALDO"."ESTUDIO" ADD CONSTRAINT "PK_ESTUDIO" PRIMARY KEY ("COD_ESTUDIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GESOALDO"."ESTUDIO" MODIFY ("COD_ESTUDIO" NOT NULL ENABLE);


  ALTER TABLE "GESOALDO"."PERSONAGEM" ADD CONSTRAINT "PK_PERSONAGEM" PRIMARY KEY ("COD_ARTISTA", "COD_FILME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GESOALDO"."PERSONAGEM" MODIFY ("COD_FILME" NOT NULL ENABLE);
  ALTER TABLE "GESOALDO"."PERSONAGEM" MODIFY ("COD_ARTISTA" NOT NULL ENABLE);


  ALTER TABLE "GESOALDO"."EMPREGADO" ADD CONSTRAINT "FKDEPTO" FOREIGN KEY ("CODDEPTO")
	  REFERENCES "GESOALDO"."DEPARTAMENTO" ("CODDEPTO") ENABLE;
  ALTER TABLE "GESOALDO"."EMPREGADO" ADD CONSTRAINT "FKGERENTE" FOREIGN KEY ("GERENTE")
	  REFERENCES "GESOALDO"."EMPREGADO" ("MATRICULA") ENABLE;


  ALTER TABLE "GESOALDO"."FILME" ADD CONSTRAINT "FK_FILME1_CATEG" FOREIGN KEY ("COD_CATEG")
	  REFERENCES "GESOALDO"."CATEGORIA" ("COD_CATEG") ENABLE;
  ALTER TABLE "GESOALDO"."FILME" ADD CONSTRAINT "FK_FILME2_ESTUD" FOREIGN KEY ("COD_ESTUDIO")
	  REFERENCES "GESOALDO"."ESTUDIO" ("COD_ESTUDIO") ENABLE;


  ALTER TABLE "GESOALDO"."ITENSPEDIDO" ADD CONSTRAINT "FKIPED" FOREIGN KEY ("NUMPED")
	  REFERENCES "GESOALDO"."PEDIDO" ("NUMPED") ENABLE;
  ALTER TABLE "GESOALDO"."ITENSPEDIDO" ADD CONSTRAINT "FKIPROD" FOREIGN KEY ("CODPROD")
	  REFERENCES "GESOALDO"."PRODUTO" ("CODPROD") ENABLE;


  ALTER TABLE "GESOALDO"."PEDIDO" ADD CONSTRAINT "FKPEDCLI" FOREIGN KEY ("CODCLI")
	  REFERENCES "GESOALDO"."CLIENTE" ("CODCLI") ENABLE;
  ALTER TABLE "GESOALDO"."PEDIDO" ADD CONSTRAINT "FKPEDVEND" FOREIGN KEY ("CODVEND")
	  REFERENCES "GESOALDO"."VENDEDOR" ("CODVEND") ENABLE;


  ALTER TABLE "GESOALDO"."PERSONAGEM" ADD CONSTRAINT "FK_PERSONAGEM1_FILME" FOREIGN KEY ("COD_FILME")
	  REFERENCES "GESOALDO"."FILME" ("COD_FILME") ENABLE;
  ALTER TABLE "GESOALDO"."PERSONAGEM" ADD CONSTRAINT "FK_PERSONAGEM2_ARTIS" FOREIGN KEY ("COD_ARTISTA")
	  REFERENCES "GESOALDO"."ARTISTA" ("COD_ARTISTA") ENABLE;


  ALTER TABLE "GESOALDO"."PROFESSOR" ADD CONSTRAINT "FK_PROF_DISC" FOREIGN KEY ("COD_DISC")
	  REFERENCES "GESOALDO"."DISCIPLINA" ("COD_DISC") ENABLE;
